<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forum Post</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #007bff;
        }
        .content {
            margin: 20px;
        }
        .content img {
            max-width: 100%;
            height: auto;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $forum->title }}</h1>
        <p>Published on {{ $forum->created_at->format('d M Y') }}</p>
    </div>

    <div class="content">
        @if($forum->image)
            <img src="{{ public_path('storage/' . $forum->image) }}" alt="Forum Image">
        @endif
        <p>{!! nl2br(e($forum->content)) !!}</p>
    </div>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} | {{ date('d M Y, H:i') }}</p>
    </div>
</body>
</html>
